# libraries

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import sklearn

# IMPORTING DATA

In [5]:
Employee_data = pd.read_csv('data/Employee_Performance_Retention.csv')

In [13]:
Employee_data.head()

,Age,Department,Years_of_Experience,Monthly_Working_Hours,Training_Hours_per_Year,Performance_Rating,Job_Satisfaction_Level,Promotion_in_Last_2_Years,Attrition
0,59,Sales,27,135,30,3,Medium,Yes,No
1,49,Tech,13,132,36,5,Medium,Yes,Yes
2,35,Operations,16,197,11,5,Low,No,No
3,28,HR,23,204,36,3,High,No,No
4,41,Operations,33,192,36,2,Medium,No,No

In [14]:
df = Employee_data.copy()

In [20]:
df.columns

Index(['Age', 'Department', 'Years_of_Experience', 'Monthly_Working_Hours',
       'Training_Hours_per_Year', 'Performance_Rating',
       'Job_Satisfaction_Level', 'Promotion_in_Last_2_Years', 'Attrition'],
      dtype='object')

In [22]:
df.head()

,Age,Department,Years_of_Experience,Monthly_Working_Hours,Training_Hours_per_Year,Performance_Rating,Job_Satisfaction_Level,Promotion_in_Last_2_Years,Attrition
0,59,Sales,27,135,30,3,Medium,Yes,No
1,49,Tech,13,132,36,5,Medium,Yes,Yes
2,35,Operations,16,197,11,5,Low,No,No
3,28,HR,23,204,36,3,High,No,No
4,41,Operations,33,192,36,2,Medium,No,No

# DROPPED THE ID COLUMN

# PRE PROCESSING

In [23]:
df.isnull().sum()

Age                          0
Department                   0
Years_of_Experience          0
Monthly_Working_Hours        0
Training_Hours_per_Year      0
Performance_Rating           0
Job_Satisfaction_Level       0
Promotion_in_Last_2_Years    0
Attrition                    0
dtype: int64

In [25]:
for column in df.columns:
    print(df[column].value_counts())
    print("*"*20)

Age
46    263
37    256
48    253
33    248
43    247
59    242
38    242
45    242
55    240
41    239
57    239
49    238
35    238
32    237
22    237
52    236
42    236
44    235
31    234
40    230
28    230
24    230
54    229
36    227
29    227
39    226
50    225
53    224
56    224
26    224
58    222
23    221
30    221
21    220
34    216
25    213
27    199
51    196
47    194
Name: count, dtype: int64
********************
Department
Operations    1843
HR            1833
Sales         1788
Finance       1787
Tech          1749
Name: count, dtype: int64
********************
Years_of_Experience
16    292
12    277
15    277
27    273
10    271
32    266
6     266
21    265
9     263
22    263
28    261
31    261
2     260
3     260
13    259
17    259
1     258
8     257
14    257
24    257
23    256
20    255
11    253
4     251
34    250
18    250
30    249
7     248
33    247
19    245
26    245
29    243
5     237
0     236
25    233
Name: count, dtype: int64
********************
Monthly_Working_Hours
163    93
206    88
240    88
124    86
172    84
       ..
228    55
215    55
186    54
153    53
220    53
Name: count, Length: 130, dtype: int64
********************
Training_Hours_per_Year
35    215
21    204
41    202
29    200
27    197
3     197
33    193
28    192
44    191
7     191
22    190
20    189
0     188
5     188
23    186
38    185
40    185
2     184
1     184
19    182
30    182
9     182
16    182
43    182
6     182
4     180
25    179
15    179
49    179
46    178
42    177
37    176
10    175
39    174
34    173
26    173
11    172
8     172
17    171
36    169
31    168
45    166
12    164
47    164
13    164
14    163
48    162
32    162
24    155
18    152
Name: count, dtype: int64
********************
Performance_Rating
3    3630
4    2191
2    1351
5     921
1     907
Name: count, dtype: int64
********************
Job_Satisfaction_Level
Medium    4501
Low       2719
High      1780
Name: count, dtype: int64
********************
Promotion_in_Last_2_Years
No     8074
Yes     926
Name: count, dtype: int64
********************
Attrition
No     7247
Yes    1753
Name: count, dtype: int64
********************

In [27]:
df.head()

,Age,Department,Years_of_Experience,Monthly_Working_Hours,Training_Hours_per_Year,Performance_Rating,Job_Satisfaction_Level,Promotion_in_Last_2_Years,Attrition
0,59,Sales,27,135,30,3,Medium,Yes,No
1,49,Tech,13,132,36,5,Medium,Yes,Yes
2,35,Operations,16,197,11,5,Low,No,No
3,28,HR,23,204,36,3,High,No,No
4,41,Operations,33,192,36,2,Medium,No,No

In [32]:
Employee_data.head()

,Age,Department,Years_of_Experience,Monthly_Working_Hours,Training_Hours_per_Year,Performance_Rating,Job_Satisfaction_Level,Promotion_in_Last_2_Years,Attrition
0,59,Sales,27,135,30,3,Medium,Yes,No
1,49,Tech,13,132,36,5,Medium,Yes,Yes
2,35,Operations,16,197,11,5,Low,No,No
3,28,HR,23,204,36,3,High,No,No
4,41,Operations,33,192,36,2,Medium,No,No

In [33]:
df1=Employee_data.copy()

In [36]:
df1['Promotion_in_Last_2_Years'] = df1['Promotion_in_Last_2_Years'].map({'Yes': 1, 'No': 0},)
df1['Attrition'] = df1['Attrition'].map({'Yes': 1, 'No': 0},)
df1.head()

,Age,Department,Years_of_Experience,Monthly_Working_Hours,Training_Hours_per_Year,Performance_Rating,Job_Satisfaction_Level,Promotion_in_Last_2_Years,Attrition
0,59,Sales,27,135,30,3,Medium,1,0
1,49,Tech,13,132,36,5,Medium,1,1
2,35,Operations,16,197,11,5,Low,0,0
3,28,HR,23,204,36,3,High,0,0
4,41,Operations,33,192,36,2,Medium,0,0

In [37]:
df1.head()

,Age,Department,Years_of_Experience,Monthly_Working_Hours,Training_Hours_per_Year,Performance_Rating,Job_Satisfaction_Level,Promotion_in_Last_2_Years,Attrition
0,59,Sales,27,135,30,3,Medium,1,0
1,49,Tech,13,132,36,5,Medium,1,1
2,35,Operations,16,197,11,5,Low,0,0
3,28,HR,23,204,36,3,High,0,0
4,41,Operations,33,192,36,2,Medium,0,0

In [38]:
df2=df1.copy()
df2.head()

,Age,Department,Years_of_Experience,Monthly_Working_Hours,Training_Hours_per_Year,Performance_Rating,Job_Satisfaction_Level,Promotion_in_Last_2_Years,Attrition
0,59,Sales,27,135,30,3,Medium,1,0
1,49,Tech,13,132,36,5,Medium,1,1
2,35,Operations,16,197,11,5,Low,0,0
3,28,HR,23,204,36,3,High,0,0
4,41,Operations,33,192,36,2,Medium,0,0

In [40]:
# One-hot encode the 'Job Satisfaction Level' column and drop the first category
df2 = pd.get_dummies(df2, columns=['Job_Satisfaction_Level'], drop_first=True)
df2.head()

,Age,Department,Years_of_Experience,Monthly_Working_Hours,Training_Hours_per_Year,Performance_Rating,Promotion_in_Last_2_Years,Attrition,Job_Satisfaction_Level_Low,Job_Satisfaction_Level_Medium
0,59,Sales,27,135,30,3,1,0,False,True
1,49,Tech,13,132,36,5,1,1,False,True
2,35,Operations,16,197,11,5,0,0,True,False
3,28,HR,23,204,36,3,0,0,False,False
4,41,Operations,33,192,36,2,0,0,False,True

In [43]:

df2.head()
df3=df2.copy()
#DF3 failed

In [49]:
df5=df2.copy()

In [53]:
# Assuming your DataFrame is named 'df5'
df5 = pd.get_dummies(df5, columns=['Department'], drop_first=True)

KeyError: "None of [Index(['Department'], dtype='object')] are in the [columns]"

In [54]:
df5.head()

,Age,Years_of_Experience,Monthly_Working_Hours,Training_Hours_per_Year,Performance_Rating,Promotion_in_Last_2_Years,Attrition,Job_Satisfaction_Level_Low,Job_Satisfaction_Level_Medium,Department_HR,Department_Operations,Department_Sales,Department_Tech
0,59,27,135,30,3,1,0,False,True,False,False,True,False
1,49,13,132,36,5,1,1,False,True,False,False,False,True
2,35,16,197,11,5,0,0,True,False,False,True,False,False
3,28,23,204,36,3,0,0,False,False,True,False,False,False
4,41,33,192,36,2,0,0,False,True,False,True,False,False

In [55]:
# Assuming your DataFrame is named df4
df5 = df5.astype(int)
df5.head()

,Age,Years_of_Experience,Monthly_Working_Hours,Training_Hours_per_Year,Performance_Rating,Promotion_in_Last_2_Years,Attrition,Job_Satisfaction_Level_Low,Job_Satisfaction_Level_Medium,Department_HR,Department_Operations,Department_Sales,Department_Tech
0,59,27,135,30,3,1,0,0,1,0,0,1,0
1,49,13,132,36,5,1,1,0,1,0,0,0,1
2,35,16,197,11,5,0,0,1,0,0,1,0,0
3,28,23,204,36,3,0,0,0,0,1,0,0,0
4,41,33,192,36,2,0,0,0,1,0,1,0,0

In [56]:
df6=df5.copy()

# SCALING AND TEST TRAIN

In [57]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler


X = df6.drop('Attrition', axis=1)
y = df6['Attrition']

# Split the data into training and testing sets (e.g., 80% train, 20% test)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Initialize the StandardScaler
scaler = StandardScaler()

# Fit the scaler on the TRAINING data and transform both the training and testing sets
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

print("Shape of X_train_scaled:", X_train_scaled.shape)
print("Shape of X_test_scaled:", X_test_scaled.shape)
print("Shape of y_train:", y_train.shape)
print("Shape of y_test:", y_test.shape)

Shape of X_train_scaled: (7200, 12)
Shape of X_test_scaled: (1800, 12)
Shape of y_train: (7200,)
Shape of y_test: (1800,)

In [58]:
# RANDOM FOREST CLASSIFICATION

# RANDOM FOREST

In [62]:
from sklearn.ensemble import RandomForestClassifier

# Use the 'balanced' class_weight to penalize errors on the minority class more
rf_classifier = RandomForestClassifier(n_estimators=100, class_weight='balanced', random_state=42)

# Now train this new model
rf_classifier.fit(X_train_scaled, y_train)

RandomForestClassifier(class_weight='balanced', random_state=42)

In [63]:
# Use the trained model to predict the 'Attrition' for the test set
y_pred = rf_classifier.predict(X_test_scaled)

In [66]:
from sklearn.metrics import classification_report


print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.80      1.00      0.89      1446
           1       0.50      0.01      0.01       354

    accuracy                           0.80      1800
   macro avg       0.65      0.50      0.45      1800
weighted avg       0.74      0.80      0.72      1800

# XG BOOST

In [74]:
from xgboost import XGBClassifier
from sklearn.metrics import classification_report


scale_pos_weight = (len(y_train[y_train == 0]) / len(y_train[y_train == 1]))


xgb_classifier = XGBClassifier(
    objective='binary:logistic',  # For binary classification
    n_estimators=100,
    learning_rate=0.1,
    scale_pos_weight=scale_pos_weight,
    random_state=42
)


xgb_classifier.fit(X_train_scaled, y_train)


y_pred_xgb = xgb_classifier.predict(X_test_scaled)

In [75]:

print(classification_report(y_test, y_pred_xgb))

              precision    recall  f1-score   support

           0       0.80      0.72      0.76      1446
           1       0.20      0.28      0.23       354

    accuracy                           0.63      1800
   macro avg       0.50      0.50      0.50      1800
weighted avg       0.68      0.63      0.66      1800

In [71]:
from imblearn.over_sampling import SMOTE
from xgboost import XGBClassifier

# Resample the training data with SMOTE
smote = SMOTE(random_state=42)
X_train_resampled, y_train_resampled = smote.fit_resample(X_train_scaled, y_train)

# Initialize the XGBoost model without scale_pos_weight
xgb_classifier = XGBClassifier(random_state=42)

# Fit the model on the resampled data
xgb_classifier.fit(X_train_resampled, y_train_resampled)

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, device=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric=None, feature_types=None,
              feature_weights=None, gamma=None, grow_policy=None,
              importance_type=None, interaction_constraints=None,
              learning_rate=None, max_bin=None, max_cat_threshold=None,
              max_cat_to_onehot=None, max_delta_step=None, max_depth=None,
              max_leaves=None, min_child_weight=None, missing=nan,
              monotone_constraints=None, multi_strategy=None, n_estimators=None,
              n_jobs=None, num_parallel_tree=None, ...)

In [76]:
from sklearn.metrics import accuracy_score

accuracy = accuracy_score(y_test, y_pred_xgb)
print(f"Accuracy: {accuracy:.4f}")

Accuracy: 0.6344

In [77]:
from sklearn.metrics import classification_report

print(classification_report(y_test, y_pred_xgb))

              precision    recall  f1-score   support

           0       0.80      0.72      0.76      1446
           1       0.20      0.28      0.23       354

    accuracy                           0.63      1800
   macro avg       0.50      0.50      0.50      1800
weighted avg       0.68      0.63      0.66      1800

# SVM CLASSIFIER

In [81]:
from sklearn.svm import SVC
from sklearn.metrics import classification_report


svm_classifier = SVC(class_weight='balanced', random_state=42)

svm_classifier.fit(X_train_scaled, y_train)


y_pred_svm = svm_classifier.predict(X_test_scaled)

In [82]:

print(classification_report(y_test, y_pred_svm))

              precision    recall  f1-score   support

           0       0.80      0.55      0.65      1446
           1       0.19      0.44      0.27       354

    accuracy                           0.53      1800
   macro avg       0.50      0.49      0.46      1800
weighted avg       0.68      0.53      0.58      1800

In [83]:
from sklearn.svm import SVC
from sklearn.model_selection import GridSearchCV
from sklearn.metrics import classification_report


param_grid = {
    'C': [0.1, 1, 10, 100],  # Controls the penalty for misclassification
    'gamma': ['scale', 'auto', 0.1, 1], # Defines the influence of a single training example
    'kernel': ['rbf'] # Using the Radial Basis Function (RBF) kernel
}

grid_search = GridSearchCV(
    SVC(class_weight='balanced', random_state=42),
    param_grid,
    cv=5,
    scoring='recall' # We are optimizing for recall, which is a key metric for this problem
)

grid_search.fit(X_train_scaled, y_train)


print("Best parameters found: ", grid_search.best_params_)
print("Best recall score on training set: ", grid_search.best_score_)

best_svm_model = grid_search.best_estimator_
y_pred_tuned_svm = best_svm_model.predict(X_test_scaled)

print("\nClassification Report for Tuned SVM Model:")
print(classification_report(y_test, y_pred_tuned_svm))

Best parameters found:  {'C': 1, 'gamma': 'auto', 'kernel': 'rbf'}
Best recall score on training set:  0.4367255504352278

Classification Report for Tuned SVM Model:
              precision    recall  f1-score   support

           0       0.80      0.55      0.65      1446
           1       0.19      0.44      0.27       354

    accuracy                           0.53      1800
   macro avg       0.50      0.49      0.46      1800
weighted avg       0.68      0.53      0.58      1800